services:
  test-db:
    image: postgres
    container_name: my_postgres_test_db
    restart: no # on-failure:5, unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME:-test_db}
    ports:
      - '${DATABASE_PORT:-5433}:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - amarom-edge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  pgdata_test:
    driver: local

networks:
  amarom-edge:
